#!/bin/bash

# usage
# chmod +x ./sequences_of_objects
# ./sequences_of_objects [painting_path]

cd object_detector/checkpoints
unzip checkpoints.zip
cd ../notebooks
python object_detection_save_results.py $1     # object detection
cd ../../sequence_classifier
python composition_classification.py $1        # composition classification
